version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build:    
    docker:
      - image: cimg/openjdk:11.0
    steps:
      # Checkout the code as the first step.
      - checkout

      # Build JAR file
      - run:
          name: Maven build
          command: mvn -B -DskipTests clean package

      # Save shared data
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - target/todo-backend-*.jar
            - docker

      # Then run your tests!
      #- run:
      #    name: Test
      #    command: mvn test
      
  push:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      BUILD_NUMBER: << pipeline.number >>
    steps:
      # Access shared data
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .

      # Install Docker
      - setup_remote_docker

      # Echo build number
      - run:
          name: Echo build number
          command: echo $BUILD_NUMBER

      # Login into Docker Hub
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin     

      # Build Docker image
      - docker/build:
          docker-context: .
          path: ./docker
          dockerfile: todo-backend.dockerfile
          image: ddrram/todo-backend
          tag: 1.3.$BUILD_NUMBER

      # Push Docker image
      - docker/push:
          image: ddrram/todo-backend           
          tag: 1.3.$BUILD_NUMBER
  deploy:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      BUILD_NUMBER: << pipeline.number >>
      DEPLOY_SCRIPT: ~/git/todo-backend/deploy.sh
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2b:a4:ba:38:78:e6:13:5e:53:bc:8e:8b:59:3a:c0:fe"
      - run:
          name: Add known host
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "echo 1.3.$BUILD_NUMBER > ~/logs/todo-backend.log && chmod 755 $DEPLOY_SCRIPT && bash $DEPLOY_SCRIPT && exit"

workflows:
  Maven:
    jobs:
      - build
      - push:
          context:
            - build-context
          requires:
            - build
      - deploy:
          context:
            - build-context
          requires:
            - push
