version: '3'

services:

  local-frontend:
    container_name: local-frontend
    image: rmetel/todo-frontend:1.1
    ports:
      - "3000:3000"

  local-db:
    container_name: local-database
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - "C:/Users/rame/db:/var/lib/mysql:rw"
