version: '3'

services:

  local-db:
    container_name: local-database
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - "C:/Users/ddr_r/mysql:/var/lib/mysql:rw"


# docker-compose -f docker/docker-compose-mysql.yaml up -d