version: '3'

services:
  todo-nginx:
    container_name: todo-nginx
    image: ddrram/todo-nginx-cert:1.1.3
    ports:
      - "80:80"
#      - "443:443"
    networks:
      - todo-app
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped

  todo-certbot:
    image: certbot/certbot
    container_name: todo-certbot
#    depends_on:
#      - todo-nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --test-cert --email ralph.metel@gmx.de -d todo-app.tech --agree-tos
    networks:
      - todo-app

networks:
  todo-app: {}

# docker-compose -f docker/docker-compose-cert.yaml up -d