version: '3'

services:

  todo-nginx:
    container_name: todo-nginx
    image: rmetel/todo-nginx:1.3
    ports:
      - "80:80"
    depends_on:
      - todo-backend
      - todo-frontend
    networks:
      - isolated

  todo-frontend:
    container_name: todo-frontend
    image: rmetel/todo-frontend:1.10
    ports:
      - "3000:3000"
    networks:
      - isolated

  todo-backend:
    container_name: todo-backend
    image: rmetel/todo-backend:1.0.20
    ports:
      - "5000:5000"
    depends_on:
      - todo-database
    networks:
      - isolated
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://todo-database:3306/todo?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "todo",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.datasource.initialization-mode": "always",
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
      }'

  todo-database:
    container_name: todo-database
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - "C:/Users/rame/db:/var/lib/mysql:rw"
    networks:
      - isolated

networks:
  isolated: {}

volumes:
  todo-database : {}