version: '3'

services:
  todo-nginx:
    container_name: todo-nginx
    image: ddrram/todo-nginx-cert:1.1.3
    ports:
      - "80:80"
    networks:
      - todo-app
    volumes:
      - /root/usr/share/certbot/conf:/etc/letsencrypt
      - /root/usr/share/certbot/www:/var/www/certbot
    restart: unless-stopped

  todo-certbot:
    image: certbot/certbot
    container_name: todo-certbot
    depends_on:
      - todo-nginx
    volumes:
      - /root/usr/share/certbot/conf:/etc/letsencrypt
      - /root/usr/share/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ralph.metel@gmx.de -d todo-app.tech --agree-tos # --test-cert
    networks:
      - todo-app

networks:
  todo-app: {}

# docker-compose -f docker/docker-compose-cert.yaml up -d