version: '3'

services:
  todo-nginx:
    container_name: todo-nginx
    image: ddrram/todo-nginx-prod:1.2.1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - todo-backend
      - todo-frontend
    networks:
      - todo-app
    volumes:
      - /root/usr/share/certbot/conf:/etc/letsencrypt
#      - /root/usr/share/www:/var/www/certbot
    restart: unless-stopped

  todo-frontend:
    container_name: todo-frontend
    image: ddrram/todo-frontend:${TODO_FRONTEND_VERSION}
    ports:
      - "3000:3000"
    networks:
      - todo-app
    restart: unless-stopped

  todo-backend:
    container_name: todo-backend
    image: ddrram/todo-backend:${TODO_BACKEND_VERSION}
    ports:
      - "5000:5000"
    depends_on:
      - todo-db
    networks:
      - todo-app
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://todo-db:3306/todo-db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "todo",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.datasource.initialization-mode": "always",
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
      }'
    restart: unless-stopped

  todo-db:
    container_name: todo-db
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: todo-db
      MYSQL_ROOT_PASSWORD: todo
    ports:
      - "3306:3306"
    volumes:
      - "/root/usr/share/databases/todo-db:/var/lib/mysql:rw"
    networks:
      - todo-app
    restart: unless-stopped

networks:
  todo-app: {}

volumes:
  todo-db : {}

# docker-compose -f docker/docker-compose-prod.yaml up -d