---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-database
  labels:
    app: todo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-database
  template:
    metadata:
      labels:
        app: todo-database
    spec:
      containers:
        - name: todo-database
          image: mysql:8.0.30
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: todo

# run
# kubectl apply -f todo-database.deployment.yaml

# shutdown
# kubectl scale --replicas=0 deployment/todo-database