---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mysql
  labels:
    app: todo-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-mysql
  template:
    metadata:
      labels:
        app: todo-mysql
    spec:
      containers:
        - name: todo-mysql
          image: mysql:8.0.30
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: todo

# kubectl apply -f todo-mysql.deployment.yaml